plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'org.abc'
version = '1.0-SNAPSHOT'

def lwjglVersion = "3.3.6"

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = '21'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = 'org.abc.Main'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation "org.lwjgl:lwjgl:$lwjglVersion"
    implementation "org.lwjgl:lwjgl-opengl:$lwjglVersion"
    implementation "org.lwjgl:lwjgl-glfw:$lwjglVersion"
    implementation "org.lwjgl:lwjgl-stb:$lwjglVersion"

    runtimeOnly "org.lwjgl:lwjgl:$lwjglVersion:natives-windows"
    runtimeOnly "org.lwjgl:lwjgl:$lwjglVersion:natives-linux"
    runtimeOnly "org.lwjgl:lwjgl:$lwjglVersion:natives-macos"

    runtimeOnly "org.lwjgl:lwjgl-opengl:$lwjglVersion:natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-opengl:$lwjglVersion:natives-linux"
    runtimeOnly "org.lwjgl:lwjgl-opengl:$lwjglVersion:natives-macos"

    runtimeOnly "org.lwjgl:lwjgl-glfw:$lwjglVersion:natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-glfw:$lwjglVersion:natives-linux"
    runtimeOnly "org.lwjgl:lwjgl-glfw:$lwjglVersion:natives-macos"

    runtimeOnly "org.lwjgl:lwjgl-stb:$lwjglVersion:natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-stb:$lwjglVersion:natives-linux"
    runtimeOnly "org.lwjgl:lwjgl-stb:$lwjglVersion:natives-macos"
}

test {
    useJUnitPlatform()
}